name: Build Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: orcaslicer-novnc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (without pushing)
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true  # Ensures image is available locally
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Save Docker image as artifact
        run: |
          docker save -o docker-image.tar ${{ env.IMAGE_NAME }}:latest

      - name: Upload Docker image artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: docker-image.tar
          path: docker-image.tar
          compression-level: 0  # Optimized for large artifacts
          retention-days: 1
