name: Deploy to GitHub Container Registry

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: orcaslicer-novnc

jobs:
  deploy-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Download Docker image artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          name: docker-image
          path: ${{ runner.temp }}

      - name: Check downloaded artifacts
        run: ls -lah ${{ runner.temp }}

      - name: Load Docker image
        run: docker load -i ${{ runner.temp }}/docker-image.tar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GHCR
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/${{ github.repository }}:latest
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ github.repository }}:latest
          docker push ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}
